Desymfony\Route\Infrastructure\Persistence\Doctrine\Domain\Entity\DoctrineRoute:
  table: route
  type: entity
  repositoryClass: Desymfony\Route\Infrastructure\Persistence\Doctrine\Domain\Repository\DoctrineRouteRepository
  id:
    id:
      type: integer
      length: 11
      unsigned: true
      generator:
        strategy: AUTO
  manyToMany:
    pokemons:
      targetEntity: Desymfony\Route\Infrastructure\Persistence\Doctrine\Domain\Entity\DoctrinePokemon
      inversedBy: routes
      joinTable:
        name: route_pokemon
        joinColumns:
          route_id:
            referencedColumnName: id
        inverseJoinColumns:
          pokemon_id:
            referencedColumnName: id

